name: release

on:
  push:
    branches: [ main ]
    
jobs:
  draft:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: package and draft release
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./build.ps1 --stable=true
        $VERSION = Get-ChildItem -Path artifacts/*.nupkg -Name | Select-String -Pattern '\d+.\d+.\d+' | foreach {$_.Matches.Value}
        gh release create --generate-notes $VERSION
